[project]
name = "ollama-demo"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "ipython>=9.4.0",
    "openai>=1.93.0",
    "pip>=25.1.1",
]
